/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Adressbuch;

import static Adressbuch.PI.liste;
import java.awt.Color;
import java.awt.Point;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Utilities;

/**
 *
 * @author 220227
 */
public class GUI2 extends javax.swing.JFrame {

    /**
     * Creates new form GUI2
     */
    public GUI2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SuchTextFeld = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jVorname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jInformationsArea = new javax.swing.JTextArea();
        jBsuchen = new javax.swing.JButton();
        jNachname = new javax.swing.JTextField();
        jNummer = new javax.swing.JTextField();
        jAdresse = new javax.swing.JTextField();
        jBadd = new javax.swing.JButton();
        jAnzeigen = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("Vorname");

        jLabel2.setText("Nachname");

        jLabel3.setText("Telefonnummer");

        jVorname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVornameActionPerformed(evt);
            }
        });

        jLabel4.setText("Adresse");

        jLabel5.setText("Informationen");

        jInformationsArea.setColumns(20);
        jInformationsArea.setRows(5);
        jInformationsArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jInformationsArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jInformationsAreaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jInformationsArea);

        jBsuchen.setText("Suchen");
        jBsuchen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsuchenActionPerformed(evt);
            }
        });

        jNachname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNachnameActionPerformed(evt);
            }
        });

        jNummer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNummerActionPerformed(evt);
            }
        });

        jAdresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAdresseActionPerformed(evt);
            }
        });

        jBadd.setText("Add");
        jBadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaddActionPerformed(evt);
            }
        });

        jAnzeigen.setText("Anzeigen");
        jAnzeigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnzeigenActionPerformed(evt);
            }
        });

        jButton1.setText("Löschen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jAnzeigen, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SuchTextFeld, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBsuchen))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jNachname, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                            .addComponent(jVorname))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(15, 15, 15)
                                                .addComponent(jNummer, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addComponent(jAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(38, 38, 38)
                                        .addComponent(jBadd, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jVorname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jNummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jNachname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jBadd, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBsuchen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SuchTextFeld)
                        .addComponent(jAnzeigen, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jVornameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVornameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jVornameActionPerformed

    private void jNachnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNachnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNachnameActionPerformed

    private void jNummerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNummerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNummerActionPerformed

    private void jAdresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAdresseActionPerformed

    private void jBsuchenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsuchenActionPerformed
        
        for (int i = 0; i < PI.liste.size(); i++) {
            if (PI.liste.get(i).getVorname().equals(SuchTextFeld.getText())) {
                jInformationsArea.setText("Die person wurde auf Eintrag "+(i+1)+" gefunden.");
                break;
            }else{
                  if (PI.liste.get(i).getNachname().equals(SuchTextFeld.getText())) {
                jInformationsArea.setText("Die person wurde auf Eintrag "+(i+1)+" gefunden.");
                      break;
            }else{
                      if (PI.liste.get(i).getTelefonnummer().equals(SuchTextFeld.getText())) {
                jInformationsArea.setText("Die person wurde auf Eintrag "+(i+1)+" gefunden.");
                          break;
            }else{
                          if (PI.liste.get(i).getAdresse().equals(SuchTextFeld.getText())) {
                jInformationsArea.setText("Die person wurde auf Eintrag "+(i+1)+" gefunden.");
                              break;
            }else{
                           jInformationsArea.setText("Es konte niemand gefunden werden");   
                          }
                      }
                  }  
                    }
        }
        
    }//GEN-LAST:event_jBsuchenActionPerformed
 
    private void jBaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaddActionPerformed
        int x=0;
        if(jVorname.getText().length()<1){
            jInformationsArea.setText("Fehler");
            x--;
        }else{
            if(jNachname.getText().length()<1){
            jInformationsArea.setText("Fehler");
            x--;
        }else{
            if(jNummer.getText().length()<1){
            jInformationsArea.setText("Fehler");
            x--;
        }else{
            if(jAdresse.getText().length()>0 && x==0){
                
          PI pi = new PI(jVorname.getText(),jNachname.getText(),jNummer.getText(),jAdresse.getText());
          PI.liste.add(pi);
          jVorname.setText("");
           jNachname.setText("");
            jNummer.setText("");
             jAdresse.setText("");
                jInformationsArea.setText("Erfolgreich Hinzgefügt");
        }else{
           jInformationsArea.setText("Fehler");
                
                
        
        }
        }
        }
        }
    }//GEN-LAST:event_jBaddActionPerformed

    private void jAnzeigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnzeigenActionPerformed
        // TODO add your handling code here:
        anzeigen();
    }//GEN-LAST:event_jAnzeigenActionPerformed

    private void jInformationsAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInformationsAreaMouseClicked
    try {                                               
        //quelle: Stackoverflow
        Point pt = jInformationsArea.getMousePosition();
        int ss = jInformationsArea.getSelectionStart();
        String str = jInformationsArea.getText().substring(0, ss) + " ";
        int line = str.split("\n").length;
        
        // zeilen färben
        int startOfLine = jInformationsArea.getLineStartOffset(line-1);
        int endOfLine = jInformationsArea.getLineEndOffset(line-1);
        
        try {
           //macht line gelb
            DefaultHighlighter.DefaultHighlightPainter highlightPainter =
                    new DefaultHighlighter.DefaultHighlightPainter(Color.YELLOW);
            jInformationsArea.getHighlighter().addHighlight(startOfLine, endOfLine, highlightPainter);
        } catch (BadLocationException e) {
        }
        
       loeschen(false,startOfLine,endOfLine);
       //IDE wollte das so
    } catch (BadLocationException ex) {
            Logger.getLogger(GUI2.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    }//GEN-LAST:event_jInformationsAreaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            loeschen(true,0,0);
        } catch (BadLocationException ex) {
            Logger.getLogger(GUI2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
 
                                           
       public void loeschen( boolean q,int x,int y) throws BadLocationException {
          if(q==true){
              //löschen der zeile
              if(x==y){
               PI.liste.remove(x);   
              }
             
              
              
              q=false;
          }
           
           
       }
    
    
   
    
    public void anzeigen(){
       
        jInformationsArea.setText("Liste-------->\n");
       for (int i = 0; i < liste.size(); i++) {
           jInformationsArea.append((1+i)+": "+PI.liste.get(i).getVorname()+"     "+PI.liste.get(i).getNachname()+"     "+PI.liste.get(i).getTelefonnummer()+"     "+PI.liste.get(i).getAdresse()+"\n");
       }
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SuchTextFeld;
    private javax.swing.JTextField jAdresse;
    private javax.swing.JButton jAnzeigen;
    private javax.swing.JButton jBadd;
    private javax.swing.JButton jBsuchen;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextArea jInformationsArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jNachname;
    private javax.swing.JTextField jNummer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jVorname;
    // End of variables declaration//GEN-END:variables
}
